version: '3.8'

services:
  music_crs:
    image: music_crs:latest
    network_mode: "host"
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    group_add:
      - "video"
    ipc: "host"
    cap_add:
      - "SYS_PTRACE"
    security_opt:
      - "seccomp=unconfined"


