version: '3.8'

services:
  music_crs:
    build:
      dockerfile: Dockerfile
    network_mode: "host"
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    volumes:
      - ./local_model_cache:/music_crs/local_model_cache:Z
    group_add:
      - "video"
    ipc: "host"
    cap_add:
      - "SYS_PTRACE"
    security_opt:
      - "seccomp=unconfined"


